Feature/mirror on windows
cryptomator/jfuse pull request #2
Opened 2022-03-18 09:51 UTC by infeo

This PR:
* updates the windows jfuse implementation to the same state as the mac and linux impl (mount, rund and unmount without errors or exceptions)
* activates the windows mirror integration tests on the CI

Regarding 25603a02f7cdf2e1189a938cec49a196ae3adddb:
Due to the first [failed CI run](https://github.com/cryptomator/jfuse/actions/runs/1999695202) with unclear error message, i thought maybe we have to mount into a directory and prepared everything in the integration test for it. Because I'm messy i forgot to set the property in the ci script, but the tests were successful nonetheless. 🤷

2022-03-18 10:37 UTC, overheadhunter requested changes

2022-03-18 10:37 UTC, overheadhunter commented on jfuse-examples/src/main/java/org/cryptomator/jfuse/examples/PosixMirrorFileSystem.java
> +			System.out.println("Enter a anything to unmount...");
```suggestion
			LOG.info("Enter a anything to unmount...");
```

2022-03-18 10:37 UTC, overheadhunter commented on jfuse-examples/src/main/java/org/cryptomator/jfuse/examples/WindowsMirrorFileSystem.java
> +			System.out.println("Enter a anything to unmount...");
```suggestion
			LOG.info("Enter a anything to unmount...");
```

2022-03-18 10:37 UTC, overheadhunter commented on jfuse-tests/src/test/java/org/cryptomator/jfuse/tests/MirrorIT.java
> +			}
this doesn't get set during CI build,  does it? Is it required? Maybe we can use the "find any free drive letter" function from Cryptomator instead?

2022-03-18 10:37 UTC, overheadhunter commented on jfuse-tests/src/test/java/org/cryptomator/jfuse/tests/MirrorIT.java
> +				mirror = Path.of(ciMountPath).resolve("mnt");
Oh right, WinFSP supports mounting to (non-existing) paths now! In this case, remove the "drive letter" thing from this test alltogether

2022-03-18 10:37 UTC, overheadhunter commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +		fuseExit();
please mark with TODO for now, as we're not sure about the final API for unmounting

2022-03-18 10:37 UTC, overheadhunter commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +	}
please mark with TODO for now, as we're not sure about the final API for unmounting

2022-03-18 10:54 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +		fuseExit();
Does the intellij package also provide some sort of `@Incubating` annotation? If so, we could use this one instead.

2022-03-18 10:58 UTC, overheadhunter commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +		fuseExit();
`@Experimental`, but this is rather for APIs not for implementation....

2022-03-18 11:24 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +		fuseExit();
`TODO` it is then!

2022-03-18 11:48 UTC, infeo commented on jfuse-tests/src/test/java/org/cryptomator/jfuse/tests/MirrorIT.java
> +				mirror = Path.of(ciMountPath).resolve("mnt");
Fixed in [dd0495e](https://github.com/cryptomator/jfuse/pull/2/commits/dd0495e1993ae85f18275273e4ac65f958c1b36c)

2022-03-18 11:48 UTC, infeo commented on jfuse-tests/src/test/java/org/cryptomator/jfuse/tests/MirrorIT.java
> +			}
see https://github.com/cryptomator/jfuse/pull/2#discussion_r829879236

2022-03-18 11:48 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +	}
Fixed in [b22aac6](https://github.com/cryptomator/jfuse/pull/2/commits/b22aac6097be1d293f8c5d146e37cb89e74d4ec5)

2022-03-18 11:48 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +		fuseExit();
Fixed in [b22aac6](https://github.com/cryptomator/jfuse/pull/2/commits/b22aac6097be1d293f8c5d146e37cb89e74d4ec5)

2022-03-18 11:49 UTC, infeo commented on jfuse-examples/src/main/java/org/cryptomator/jfuse/examples/PosixMirrorFileSystem.java
> +			System.out.println("Enter a anything to unmount...");
Fixed in [b22aac6](https://github.com/cryptomator/jfuse/pull/2/commits/b22aac6097be1d293f8c5d146e37cb89e74d4ec5)

2022-03-18 11:49 UTC, infeo commented on jfuse-examples/src/main/java/org/cryptomator/jfuse/examples/WindowsMirrorFileSystem.java
> +			System.out.println("Enter a anything to unmount...");
Fixed in [b22aac6](https://github.com/cryptomator/jfuse/pull/2/commits/b22aac6097be1d293f8c5d146e37cb89e74d4ec5)

2022-03-18 12:20 UTC, overheadhunter requested changes

2022-03-18 12:20 UTC, overheadhunter commented on jfuse-tests/src/test/java/org/cryptomator/jfuse/tests/MirrorIT.java
> +
no longer required

2022-03-18 12:20 UTC, overheadhunter commented on .github/workflows/build.yml
>      if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
can be removed, since this job depends on other jobs that have this condition already

2022-03-18 12:20 UTC, overheadhunter commented on .github/workflows/build.yml
>      if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
(I'm aware this is kind of unrelated to this PR, so feel free to ignore this and do it on develop instead)

2022-03-18 12:22 UTC, overheadhunter commented on .github/workflows/build.yml
>      if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
ok this is very ambiguous. This comment refers to line 76

2022-03-21 17:06 UTC, infeo commented on jfuse-tests/src/test/java/org/cryptomator/jfuse/tests/MirrorIT.java
> +
Fixed in https://github.com/cryptomator/jfuse/pull/2/commits/cb670365b986c16d72ca3af05369d40dddf62ee6

2022-03-23 11:03 UTC, overheadhunter approved these changes

2022-03-23 12:23 UTC, merged