Update project to JDK 21 and JEP 442
cryptomator/jfuse pull request #32
Opened 2023-08-15 14:51 UTC by infeo

References: [JEP 442](https://openjdk.org/jeps/442)

Notable changes are, that the lifetime of an object is now managed via the Arena, not the MemoryScope anymore. Also, jextract now creates reproducible builds, but every extraction needs its own package or otherwise previously extracted classes are overwritten.

2023-08-15 15:22 UTC, overheadhunter requested changes
So far, I only looked at the Linux aarch64 files. All my comments so far refer to all platforms.

2023-08-15 15:22 UTC, overheadhunter commented on jfuse-linux-aarch64/src/main/java/org/cryptomator/jfuse/linux/aarch64/FuseImpl.java
> +					fuse_operations.write$set(fuseOperationsStruct, fuse_operations.write.allocate(this::write, fuseArena));
Please fix the format, I can't spot the diff

2023-08-15 15:22 UTC, overheadhunter commented on jfuse-linux-aarch64/src/main/java/org/cryptomator/jfuse/linux/aarch64/extr/fuse3/constants$37.java
> +final class constants$37 {
Are you sure jextract is configured correctly? These are a lot of "constants"...

2023-08-15 15:22 UTC, overheadhunter commented on jfuse-api/src/main/java/org/cryptomator/jfuse/api/Fuse.java
> +		return r;
This doesn't loom semantically the same. I don't know what is the correct way to deal with it using the new API, but I want to be sure this behaves the same.

2023-08-15 15:22 UTC, overheadhunter commented on jfuse-linux-aarch64/src/main/java/org/cryptomator/jfuse/linux/aarch64/FuseArgs.java
> +			var cString = argv.getAtIndex(ValueLayout.ADDRESS.withoutTargetLayout().withName("arg[%d]".formatted(i)), i).reinterpret(Long.MAX_VALUE);
There might be a more convenient way to get an element from an array of pointers.

2023-08-16 09:23 UTC, infeo commented on jfuse-linux-aarch64/src/main/java/org/cryptomator/jfuse/linux/aarch64/FuseArgs.java
> +			var cString = argv.getAtIndex(ValueLayout.ADDRESS.withoutTargetLayout().withName("arg[%d]".formatted(i)), i).reinterpret(Long.MAX_VALUE);
Also tought that, but honestly, i didn't found one.

As stated in the docs of [MemorySegment](https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/foreign/MemorySegment.html#wrapping-addresses), the segment returned by `getAtIndex()` has zero length and needs to be reinterpreted, otherwise calling `getUtf8String()` fails with :
```
java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ heapBase: Optional.empty address:2108151540976 limit: 0 }; new offset = 0; new length = 1
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.outOfBoundException(AbstractMemorySegmentImpl.java:426)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:407)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:69)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:124)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:448)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkBounds(AbstractMemorySegmentImpl.java:396)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkAccess(AbstractMemorySegmentImpl.java:356)
	at java.base/java.lang.invoke.VarHandleSegmentAsBytes.checkAddress(VarHandleSegmentAsBytes.java:81)
	at java.base/java.lang.invoke.VarHandleSegmentAsBytes.get(VarHandleSegmentAsBytes.java:108)
	at java.base/java.lang.foreign.MemorySegment.get(MemorySegment.java:1361)
	at java.base/jdk.internal.foreign.abi.SharedUtils.strlen(SharedUtils.java:260)
	at java.base/jdk.internal.foreign.abi.SharedUtils.toJavaStringInternal(SharedUtils.java:251)
	at java.base/java.lang.foreign.MemorySegment.getUtf8String(MemorySegment.java:1090)
```

Another approach was streaming:
```java
argv.elements(ValueLayout.ADDRESS.withoutTargetLayout())
	.map(arg -> arg.getUtf8String(0))
	.forEach(/* do smth */);
```
This fails with `java.lang.IllegalArgumentException: Segment size is not a multiple of layout size`. Possible cause is that, according to docs, the argument vector NULL terminated is.

2023-08-17 11:28 UTC, infeo commented on jfuse-api/src/main/java/org/cryptomator/jfuse/api/Fuse.java
> +		return r;
What was the rationale behind using the `whileAlive()` method?

Reading the libfuse docs, i have the impression that both, fuse_loop() and fuse_loop_mt() are blocking, but just to be sure i [asked in the libfuse discussions](https://github.com/libfuse/libfuse/discussions/826). Depending on the answer, we can skip the loop from my opinion, because the call is blocking and we assume, that the library is loaded and ready to be used with an alive Arena.

2023-08-17 11:37 UTC, infeo commented on jfuse-linux-aarch64/src/main/java/org/cryptomator/jfuse/linux/aarch64/FuseImpl.java
> +					fuse_operations.write$set(fuseOperationsStruct, fuse_operations.write.allocate(this::write, fuseArena));
done in https://github.com/cryptomator/jfuse/pull/32/commits/1b7e1ac3b814c5edb7b5d88b8cfa3f49c9cbbf9a

2023-08-22 11:24 UTC, overheadhunter commented on jfuse-api/src/main/java/org/cryptomator/jfuse/api/Fuse.java
> +		return r;
With the old API, it was my understanding that the scope could not be closed before all Runnables in `whileAlive` return.

There may be other safeguards now. In that case, a simple `return mount.loop();` would be sufficient, no need for the AtomicInteger.

2023-08-22 11:33 UTC, overheadhunter commented on jfuse-linux-aarch64/src/main/java/org/cryptomator/jfuse/linux/aarch64/FuseArgs.java
> +			var cString = argv.getAtIndex(ValueLayout.ADDRESS.withoutTargetLayout().withName("arg[%d]".formatted(i)), i).reinterpret(Long.MAX_VALUE);
what exactly is the purpose of `.withoutTargetLayout()` in this context?

2023-08-22 12:58 UTC, infeo commented on jfuse-linux-aarch64/src/main/java/org/cryptomator/jfuse/linux/aarch64/FuseArgs.java
> +			var cString = argv.getAtIndex(ValueLayout.ADDRESS.withoutTargetLayout().withName("arg[%d]".formatted(i)), i).reinterpret(Long.MAX_VALUE);
Another remnant of my learning the new API. Can be removed, because, by default the address layout does not have a target layout.

2023-08-22 13:03 UTC, infeo commented on jfuse-linux-aarch64/src/main/java/org/cryptomator/jfuse/linux/aarch64/FuseArgs.java
> +			var cString = argv.getAtIndex(ValueLayout.ADDRESS.withoutTargetLayout().withName("arg[%d]".formatted(i)), i).reinterpret(Long.MAX_VALUE);
Fixed in https://github.com/cryptomator/jfuse/pull/32/commits/4604880826fbb55bdadbc0994c769690af1a10be

2023-08-29 12:31 UTC, infeo commented on jfuse-api/src/main/java/org/cryptomator/jfuse/api/Fuse.java
> +		return r;
Changed in https://github.com/cryptomator/jfuse/pull/32/commits/0f6140167c174c82ddd42875226b4336d6bf3ba7

2023-08-29 19:27 UTC, overheadhunter approved these changes

2023-08-30 08:57 UTC, merged