Fix SIGSEV crashes by adding NULL pointer checks
cryptomator/jfuse pull request #39
Opened 2023-10-19 11:41 UTC by infeo

According to the [fuse 3.x documentation](https://github.com/libfuse/libfuse/blob/fuse-3.16.2/include/fuse.h), the methods `releasedir`, `getattr`, `chmod`, `chown`, `fsyncdir`, `truncate` and `utimens` can have NULL parameter. Before this PR this was not accounted for, leading to crashes of the JVM.

This PR fixes it. If the MemorySegment handed over to the JVM is the NULL-Pointer, the methods translate it to Javas `null` value.

2023-10-19 11:50 UTC, overheadhunter requested changes
What about `fi` in macOS? Is it always non-null in fuse 2?

2023-10-19 11:50 UTC, overheadhunter commented on jfuse-api/src/main/java/org/cryptomator/jfuse/api/util/MemoryUtils.java
> +		return MemorySegment.NULL.equals(string) ? null : string.getUtf8String(0);
Can be overloaded

```suggestion
		return toUtf8StringOrNull(string, 0);
```

2023-10-19 11:51 UTC, overheadhunter commented
Also, can you add tests for the new utility methods?

2023-10-19 11:54 UTC, infeo commented
> What about fi in macOS? Is it always non-null in fuse 2?

In fuse 2 the above methods either do not have a file info as parameter or the documentation only mentions the path to be nullable.

2023-10-19 14:59 UTC, infeo commented
> Also, can you add tests for the new utility methods?

@overheadhunter Done in https://github.com/cryptomator/jfuse/pull/39/commits/c3bb1540f6a5f9e869af1c928e8d66f93afc4327

2023-10-20 08:32 UTC, overheadhunter approved these changes

2023-10-20 10:31 UTC, merged