Migrate Windows to fuse3 API
cryptomator/jfuse pull request #7
Opened 2022-09-09 14:56 UTC by infeo

This PR migrates the windows jfuse project to use fuse3 instead of fuse2.

It had to be adjusted to winfsp specific quirks:
* Winfsp uses [fuse-3.2](https://github.com/winfsp/winfsp/blob/deee7eddedb24ba58c741cbb1421baf2e37fe5d4/inc/fuse3/fuse_common.h#L39-L40)
* even though the fuse header specifies the `fuse_loop_mt()` function, jextract was unable to extract it and `fuse_loop_mt_31()` had to be used
* to correctly call the fuse3 functions, the explicit fuse names in winfsp (`fuse3_...`) had to be used and redefinition is skipped by defining `WINFSP_DLL_INTERNAL`
* in fuse3 `fuse_parse_cmd_line(...)` is not defined. Looking at the source code it is used nonetheless:
https://github.com/winfsp/winfsp/blob/8d83d46e7f12fc1cb343f7917c6c59ee3a8fd0b6/src/dll/fuse3/fuse3.c#L37
  This works due to a longer chain of imports and since Winfsp is using this construct, i decided to also use it by adding an additonal jextract in an extra package

2022-09-10 10:03 UTC, overheadhunter requested changes
Good work, just found a few opportunities for cleanup.

2022-09-10 10:03 UTC, overheadhunter commented on jfuse-win-amd64/pom.xml
> +										<includeStruct>fuse3_loop_config</includeStruct>
`fuse3_loop_config` is unused, isn't it?

2022-09-10 10:03 UTC, overheadhunter commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/extr/fuse3_loop_config.java
> +public class fuse3_loop_config {
unused?

2022-09-12 10:30 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseMountImpl.java
> +			return fuse_h.fuse3_loop_mt_31(fuse, 0);
It is hard to document, if you just followed the linux implementaiton 😅 

The parameter is called `clone_fd`. In fuse3.2 it changed to a struct containg a field representing it , see http://libfuse.github.io/doxygen/structfuse__loop__config.html#a6a8527939446625e5466cd8baf399f08
```c
struct fuse_loop_config {
         int clone_fd;
  
         unsigned int max_idle_threads;
};
```

2022-09-12 11:23 UTC, overheadhunter commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseMountImpl.java
> +			return fuse_h.fuse3_loop_mt_31(fuse, 0);
Oh I just realized, that the jextracted function uses the name `clone_fd` as well. I thought it was just some anonymous int. In that case, ignore my comment. We should be able to google the meaning of `clone_fd` any time, no need to document it at this place.

2022-09-12 11:24 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/extr/fuse3_loop_config.java
> +public class fuse3_loop_config {
Fixed in https://github.com/cryptomator/jfuse/pull/7/commits/2ae3e52f33e581397708336f986743dfca589850

2022-09-12 11:24 UTC, infeo commented on jfuse-win-amd64/pom.xml
> +										<includeStruct>fuse3_loop_config</includeStruct>
Fixed in https://github.com/cryptomator/jfuse/pull/7/commits/2ae3e52f33e581397708336f986743dfca589850

2022-09-12 11:24 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
>  		return delegate.access(path.getUtf8String(0), mask);
Implemented in https://github.com/cryptomator/jfuse/pull/7/commits/2ae3e52f33e581397708336f986743dfca589850

2022-09-12 11:24 UTC, infeo commented on jfuse-win-amd64/pom.xml
> +									<headerClassName>fuse_2_h</headerClassName>
Changed in https://github.com/cryptomator/jfuse/pull/7/commits/2ae3e52f33e581397708336f986743dfca589850

2022-09-12 11:24 UTC, infeo commented on jfuse-win-amd64/pom.xml
> +									<targetPackage>org.cryptomator.jfuse.win.amd64.extr_fuse2</targetPackage>
Changed in https://github.com/cryptomator/jfuse/pull/7/commits/2ae3e52f33e581397708336f986743dfca589850

2022-09-12 11:31 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +				fuse_timespec.tv_nsec$set(segment, 0); //TODO: use something like stat_h.UTIME_NOW())
i reverted the comment to its original in https://github.com/cryptomator/jfuse/pull/7/commits/a0b83c8c2745c89fb3cea2f65e36f169b652534d

2022-09-12 11:39 UTC, overheadhunter approved these changes

2022-09-12 11:41 UTC, merged