Windows: Poll loop to check if mount is truly done
cryptomator/jfuse pull request #9
Opened 2022-09-14 10:54 UTC by infeo

Several times in the past CI tests on Windows failed due for the mount not being ready, although `fuse_init()` was already called.

jfuse uses https://github.com/winfsp/winfsp on Windows and according to its owner, there is no proper way of checking at what point the filesystem is accessible from the outside (see https://github.com/winfsp/winfsp/discussions/440). It was suggested to poll the volume until it successfully returns, but query the volume itself on the one hand requires using the native `CreateFileW` function and on the other admin rights.

The now implemented solution blocks the mount method until the fuse filesystem recieves a `getAttr(...)` call to a specific, hardcoded path.

2022-09-14 12:03 UTC, overheadhunter requested changes
I think I found a more elegant means for synchronization, which kills two birds with one stone.

2022-09-14 12:03 UTC, overheadhunter commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +				Thread.sleep(333);
If `getattr` is called and `accessProbeSuccess` is set to true, we will still sleep one last time. Which is not necessary.

If we replaced the `AtomicBoolean` with a `CountDownLatch`, we could instead use a do-while loop with `probeSucceeded.await(333, TimeUnit.MILLIS)` as the loop's condition.

2022-09-14 12:05 UTC, overheadhunter commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +				Thread.sleep(333);
which also reads like prosa:

> do read attributes while awaiting the probe

2022-09-14 13:19 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +			var pathObj = path.getUtf8String(0);
Implemented in https://github.com/cryptomator/jfuse/pull/9/commits/b33dabc0cad8020b1a14d6ae3c3e71d57f0858f5

2022-09-14 13:19 UTC, infeo commented on jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java
> +				Thread.sleep(333);
Implemented in https://github.com/cryptomator/jfuse/pull/9/commits/b33dabc0cad8020b1a14d6ae3c3e71d57f0858f5

2022-09-14 13:23 UTC, overheadhunter approved these changes

2022-09-14 13:33 UTC, merged

2022-09-15 17:18 UTC, overheadhunter commented
I just noticed that we're waiting indefinitely, if the file system doesn't [support](https://github.com/cryptomator/jfuse/blob/66827353f9e351b8cfe0cbb958da61f8227bcedc/jfuse-api/src/main/java/org/cryptomator/jfuse/api/FuseOperations.java#L47-L50) `getattr`.

We should rather always set `fuse_operations.getattr`, as we have [previously done it with init](https://github.com/cryptomator/jfuse/blob/0.1.0/jfuse-win-amd64/src/main/java/org/cryptomator/jfuse/win/amd64/FuseImpl.java#L28-L50).